# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 浪尖的碎片
subtitle: 铭刻现实,映照思想
description: "年近而立，客于京数载。\n\n尝自省，可有所得？\n\n身不知所居，心不知所寄，\n\n惟身外万事为鉴，求惝恍迷离间真我。"
keywords: personal blog,coding tricks,intresting knowledges and stories
author: 金锆文 | Jin Gaowen
language: zh-CN
timezone: Asia/Shanghai
since: 2018

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jingaowen.com/
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Overriding Theme Config
theme_config:
  scheme: Gemini
  font:
    enable: true
    # host: //fonts.lug.ustc.edu.cn
    global:
      # external: true
      family: Noto Sans SC
    headings:
      # external: true
      family: Noto Serif SC
  # Setup Menu
  menu:
    home: /
    archives: /archives
    #about: /about
    #categories: /categories
    tags: /tags
    #commonweal: /404.html
  # Avatar
  avatar: 
    url: "/images/avatar1.jpg"
    rounded: true
  # Social Icons
  social:
    GitHub: https://github.com/tjbdzr 
    微博: https://weibo.com/jingaowen
    知乎: http://zhihu.com/people/jingaowen
  # Fit Social Icons
  social_icons:
    enable: true
  # add site-subtitle to index page 
  index_with_subtitle: false
  # improve seo
  seo: true
  # comment system: gitalk
  comments:
    active: gitalk
  gitalk:
    enable: true
    github_id: tjbdzr
    repo: tjbdzr.github.io
    client_id: 3f38e03a1dfe1130d0f0
    client_secret: 11bd5b89cb7effd1c9db5fb887e70cdff9dbb953
    admin_user: tjbdzr
    create_issue_manually: false
    distraction_free_mode: true
    language: zh-CN

# Creative Commons 4.0 International License.
# https://creativecommons.org/share-your-work/licensing-types-examples
# Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons:
    license: by-nc-sa
    sidebar: true
    post: false

# Wordcount display
symbols_count_time:
    symbols: true
    time: true
    total_symbols: true
    total_time: true

# Improve SEO
sitemap: 
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
baidu_url_submit:
  count: 1 ## 提交最新的一个链接
  host:  jingaowen.com ## 在百度站长平台中注册的域名
  token: #your_token ## 请注意这是您的秘钥，以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址，新链接会保存在此文本文档里
robotstxt:
  useragent: "*"
  disallow:
    - /vendors/
    - /js/
    - /css/
    - /fonts/
    - /vendors/
    - /fancybox/
  allow:
    - /
    - /archives/
    - /categories/
    - /tags/
  sitemap: 
    - /sitemap.xml
    - /baidusitemap.xml
    - /search.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gh_token@github.com/tjbdzr/tjbdzr.github.io.git
  # repo: https://github.com/tjbdzr/jingaowen.github.io
  branch: master
# deploy:
#   type: baidu_url_submitter #暂不使用
